version: '3'
services:
  db:
    image: postgres
    ports: 
      - "5432:5432"
  web: 
    depends_on:
      - db
    build: .
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
    volumes: 
      - .:/Bookmarks
    ports:
      - "3000:3000"
    